/**
 * SoftLab.rs.FoodLab.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.api.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param mealId 
 * @param mealName 
 * @param count 
 * @param employeeId 
 * @param employeeFirstName 
 * @param employeeLastName 
 */

data class FavoriteMeal (

    @Json(name = "mealId")
    val mealId: java.util.UUID? = null,

    @Json(name = "mealName")
    val mealName: kotlin.String? = null,

    @Json(name = "count")
    val count: kotlin.Int? = null,

    @Json(name = "employeeId")
    val employeeId: java.util.UUID? = null,

    @Json(name = "employeeFirstName")
    val employeeFirstName: kotlin.String? = null,

    @Json(name = "employeeLastName")
    val employeeLastName: kotlin.String? = null

)

