/**
 * SoftLab.rs.FoodLab.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.api.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param employeeId 
 * @param employeeFirstName 
 * @param employeeLastName 
 * @param year 
 * @param month 
 * @param amount 
 */

data class MonthlySpending (

    @Json(name = "employeeId")
    val employeeId: java.util.UUID? = null,

    @Json(name = "employeeFirstName")
    val employeeFirstName: kotlin.String? = null,

    @Json(name = "employeeLastName")
    val employeeLastName: kotlin.String? = null,

    @Json(name = "year")
    val year: kotlin.Int? = null,

    @Json(name = "month")
    val month: kotlin.Int? = null,

    @Json(name = "amount")
    val amount: kotlin.Double? = null

)

