/**
 * SoftLab.rs.FoodLab.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.api.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param employeeId 
 * @param employeeFirstName 
 * @param employeeLastName 
 * @param createDate 
 * @param mealId 
 * @param mealName 
 * @param portionId 
 * @param portionSize 
 * @param sideDishId 
 * @param sideDishName 
 * @param price 
 */

data class Order (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "employeeId")
    val employeeId: java.util.UUID? = null,

    @Json(name = "employeeFirstName")
    val employeeFirstName: kotlin.String? = null,

    @Json(name = "employeeLastName")
    val employeeLastName: kotlin.String? = null,

    @Json(name = "createDate")
    val createDate: java.time.OffsetDateTime? = null,

    @Json(name = "mealId")
    val mealId: java.util.UUID? = null,

    @Json(name = "mealName")
    val mealName: kotlin.String? = null,

    @Json(name = "portionId")
    val portionId: java.util.UUID? = null,

    @Json(name = "portionSize")
    val portionSize: kotlin.String? = null,

    @Json(name = "sideDishId")
    val sideDishId: java.util.UUID? = null,

    @Json(name = "sideDishName")
    val sideDishName: kotlin.String? = null,

    @Json(name = "price")
    val price: kotlin.Double? = null

)

